{% set name = "ete3" %}
{% set version = "3.1.3" %}
{% set sha256 = "06a3b7fa8ed90187b076a8dbbe5b1b62acee94201d3c6e822f55f449601ef6f2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ete3-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --use-pep517 -vv
  entry_points:
    - ete3 = ete3.tools.ete:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six
    - lxml
    - numpy
    - pyqt >=5.15.*
    - scipy
    - xorg-libxext
    - xorg-xextproto
    - xorg-libxdmcp
    - xorg-libsm
    - xorg-libxrender
    - xorg-libxau

test:
  imports:
    - ete3
    - ete3.clustering
    - ete3.coretype
    - ete3.evol
    - ete3.ncbi_taxonomy
    - ete3.nexml
    - ete3.orthoxml
    - ete3.parser
    - ete3.phylo
    - ete3.phyloxml
    - ete3.tools
    - ete3.treeview
    - ete3.utils
    - ete3.webplugin
  commands:
    - ete3 --help
    # ete3 cmdline tools not officially supported on win
    # https://groups.google.com/d/msg/etetoolkit/G3QmfxK1Vuk/txqlTTjLEAAJ
    - ete3 build check  # [not win]

about:
  home: "http://etetoolkit.org"
  summary: "A Python package for building, comparing, annotating, manipulating, and visualising trees. It provides a comprehensive API and a collection of command line tools, including utilities to work with the NCBI taxonomy tree."
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  dev_url: "https://github.com/etetoolkit/ete"
  doc_url: "http://etetoolkit.org/docs/latest/tutorial/index.html"

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
