{% set name = "ete3" %}
{% set version = "3.1.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "4fc987b8c529889d6608fab1101f1455cb5cbd42722788de6aea9c7d0a8e59e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}
  patches:
    - import.patch

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ete3 = ete3.tools.ete:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - lxml
    - numpy
    - pyqt >=4.11.*,<5
    - scipy
    - xorg-libxext
    - xorg-xextproto
    - xorg-libxdmcp
    - xorg-libsm
    - xorg-libxrender
    - xorg-libxau

test:
  imports:
    - ete3
    - ete3.clustering
    - ete3.coretype
    - ete3.evol
    - ete3.ncbi_taxonomy
    - ete3.nexml
    - ete3.orthoxml
    - ete3.parser
    - ete3.phylo
    - ete3.phyloxml
    - ete3.tools
    - ete3.treeview
    - ete3.utils
    - ete3.webplugin

  commands:
    - ete3 --help
    - ete3 mod --help
    # ete3 cmdline tools not officially supported on win
    # https://groups.google.com/d/msg/etetoolkit/G3QmfxK1Vuk/txqlTTjLEAAJ
    - ete3 build check  # [not win]

about:
  home: http://etetoolkit.org/
  license_file: LICENSE
  license: GPL-3.0-only
  license_family: GPL
  summary: Python package for building, comparing, annotating, manipulating and visualising trees. It provides a comprehensive API and a collection of command line tools, including utilities to work with the NCBI taxonomy tree.
  doc_url: http://etetoolkit.org/
  dev_url: https://github.com/etetoolkit/ete

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
